spring:
  application:
    name: archi

  mongodb:
    host: localhost
    port: 27017
    database: archi_project

satellite:
  minio:
    access-key: minioadmin
    bucket: satellite
    endpoint: http://minio:9000
    public-endpoint: http://localhost:9000
    secret-key: password

  OWM.api-key: 728d27c984b8b3e53847db79697a23de