spring:
  application:
    name: archi

satellite:
  minio:
    access-key: minioadmin
    bucket: satellite
    endpoint: http://localhost:9000
    secret-key: password

  OWM.api-key: 728d27c984b8b3e53847db79697a23de